services:
    simple_menu.admin.menu:
        class: KunicMarko\SimpleMenuBundle\Admin\MenuAdmin
        arguments: [~, KunicMarko\SimpleMenuBundle\Entity\Menu, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: Menu }

    simple_menu.admin.menu_item:
        class: KunicMarko\SimpleMenuBundle\Admin\MenuItemAdmin
        arguments: [~, KunicMarko\SimpleMenuBundle\Entity\MenuItem, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: CMS, label: MenuItem }
